### ISSUE TITLE
[BUG] When using Flask MethodViews, request and response schemas aren't associated with the api paths

### ISSUE THREAD

**Issue by chaitanyanettem** [0b01001001/spectree#103]
**Describe the bug**
When using flask method views, even though the request and response schemas are generated in the open api spec, they are not associated with api path. So the paths field in the openapi json is this for the example below -

```json
    "paths": {
        "/api/v1/hello": {
            "post": {
                "description": "",
                "operationId": "post_/api/v1/hello",
                "parameters": [],
                "responses": {},
                "summary": "Hello <POST>",
                "tags": []
            }
        }
    }
```

**To Reproduce**
You can run the following python code and check the generated openapi spec.

```python
from flask import Flask
from flask.views import MethodView
from spectree import SpecTree, Response
from pydantic import BaseModel

app = Flask(__name__)
spectree = SpecTree('flask')


class HelloResponse(BaseModel):
    hello: str
    status: int


class HelloRequest(BaseModel):
    test: int


class Hello(MethodView):
    @spectree.validate(json=HelloRequest, resp=Response(HTTP_200=HelloResponse))
    def post():
        return {'hello': 'world', 'status': 200}


app.add_url_rule('/api/v1/hello', view_func=Hello.as_view('Hello'))
spectree.register(app)


if __name__ == '__main__':
    app.run(port=8081)
```

You can see the generated openapi spec here - [openapi spec](https://github.com/0b01001001/spectree/files/5813693/openapi.txt)

**Expected behavior**
I expected that the generated request and response schema would be associated with the `/api/v1/hello` path instead of it being blank.

**Error Message**
There's no error message as such.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Ubuntu 20.04

**Python Information (please complete the following information):**
 - Python Version - 3.8.3
 - Library Version spectree=0.3.16
 - Other dependencies Flask=1.0.2

Please let me know if you need any additional information. I'd also be happy to contribute a PR if you could direct me a bit in terms of where in the code the issue might be.

**Comment by kemingy** [comment]
Thanks for your feedback. Can you help me check if #104 can fix this?

**Comment by chaitanyanettem** [comment]
This worked. Thank you so much for the quick resolution!
