### ISSUE TITLE
[Feature] Allow for extra keywords in a routes' parameter specifications

### ISSUE THREAD

**Issue by jonathanlintott** [0b01001001/spectree#107]
The specification keywords for routes are currently hardcoded to only generate `name`, `in`, `schema`, `required`, `description` as is dictated [here](https://github.com/0b01001001/spectree/blob/master/spectree/utils.py#L43), specifically this block of code:
```
params.append(
    {
        "name": name,
        "in": "query",
        "schema": schema,
        "required": name in query.get("required", []),
        "description": schema.get("description", ""),
    }
)
```

However there are other keywords that might want to be added for different routes and models. For example the `style` and `explode` keywords as explained [here](https://swagger.io/docs/specification/serialization/). It would be beneficial to have some way for this to be passed in on a model-by-model basis for different routes. Something akin to the following:

```
params.append(
    {
        "name": name,
        "in": "query",
        "schema": schema,
        "required": name in query.get("required", []),
        "description": schema.get("description", ""),
        **extra_spec_kwargs
    }
)
```

Although I'm not sure what the best way to provide `extra_spec_kwargs` would be with the current API.

**Comment by kemingy** [comment]
Thanks for your advice.

One way to implement this is to use the `pydantic.Field(extra)`.

```py
from pydantic import BaseModel, Field


class MyModel(BaseModel):
    name: str = Field(..., explode=True, style="label")
```

So we can get the details from `MyModel.schema()`.

**Comment by jonathanlintott** [comment]
Such that the `parse_params` function would change to do something like:
```
extra = {}
for label in ("explode", "style"):
    if label in schema:
        extra[label] = schema.pop(label)
params.append(
    {
        "name": name,
        "in": "query",
        "schema": schema,
        "required": name in query.get("required", []),
        "description": schema.get("description", ""),
        **extra
    }
)
```

**Comment by kemingy** [comment]
Yeah. LGTM. If you want to create a PR for this, that'll be great if you can also add some test cases.
