### ISSUE TITLE
[Feature] Delete UnprocessableEntity from Response class

### ISSUE THREAD

**Issue by amarynets** [0b01001001/spectree#111]
In `__init__` method of `Response` class, we have the following code
```
if code_models and "HTTP_422" not in code_models:
    code_models["HTTP_422"] = UnprocessableEntity
```
It creates UnprocessableEntity and add it into response. 
```
"responses":{
   "200":{
      "description":"OK",
      "content":{
         "application/json":{
            "schema":{
               "$ref":"#/components/schemas/BaseResponse"
            }
         }
      }
   },
   "422":{
      "description":"Unprocessable Entity",
      "content":{
         "application/json":{
            "schema":{
               "$ref":"#/components/schemas/UnprocessableEntity"
            }
         }
      }
   }
}
```
Maybe there is another way to not add 422 code into response?
`@api.validate(json=BaseRequest, resp=Response(HTTP_200=BaseResponse, HTTP_422=None))`
doesn't create schema but add 422 code into response

```
"responses":{
   "422":{
      "description":"Unprocessable Entity"
   },
   "200":{
      "description":"OK",
      "content":{
         "application/json":{
            "schema":{
               "$ref":"#/components/schemas/BaseResponse"
            }
         }
      }
   }
}
```

**Comment by kemingy** [comment]
The reason why 422 is added to the response is that you have defined something that requires validation. For example, `BaseResponse`. So when there is a validation error, this library will return 422 to the client.

If you don't need any validation, then there won't be a 422. For example:

`@spec.validate()` # this won't add 422

**Comment by kemingy** [comment]
Fixed in:
* #178
