### ISSUE TITLE
[BUG] Incorrect spec definition produced when using flask's `any` converter

### ISSUE THREAD

**Issue by jonathanlintott** [0b01001001/spectree#113]
The flask plugin currently produces the following spec for a route parameter that uses the `any` converter:
```
if converter == "any":
    schema = {
        "type": "array",
        "items": {
            "type": "string",
            "enum": args,
        },
    }
```
As seen here -> https://github.com/0b01001001/spectree/blob/master/spectree/plugins/flask_plugin.py#L80

However the `any` converter behaviour is defined as the following:

> Matches one of the items provided

As seen here -> https://github.com/pallets/werkzeug/blob/8be9899df5cf8a930d961fc5295001744373da0b/src/werkzeug/routing.py#L1227

As such the correct spec produced should actually be:
```
if converter == "any":
    schema = {
        "type": "string",
        "enum": args,
    }
```

Any objection if I create a PR to fix this?

**Comment by kemingy** [comment]
Thanks for your feedback. Feel free to create a PR.
