### ISSUE TITLE
[New Feature] Support offline environment to use this library

### ISSUE THREAD

**Issue by luolingchun** [0b01001001/spectree#119]
Can we consider integrating **static files** to ensure that **swagger UI** can be used in offline environment？

**Comment by kemingy** [comment]
I just checked the static files. It mainly contains two sources:

* https://fonts.googleapis.com
* https://cdn.jsdelivr.net/npm/

There are several solutions:

1. store these files in this library as extra data
    * need to update with this library
2. pack these files into another library and use `pip install spectree[offline]` to install
    * can update separately

By the way, GitLab already supports rendering swagger UI with YAML/JSON file. So you can upload the generated `openapi.json` file to the GitLab repo for offline usage.

**Comment by luolingchun** [comment]
Thank for your reply.
In my opinion, the first scheme is simpler for users.  As before, users do not need to consider configuring static files.
If you agree, I can submit pull requests or you can handle it yourself.

**Comment by kemingy** [comment]
Welcome PR.

I have some concerns about this one.

1. The offline mode should be an opt-in feature. By default, we should use the CDN to get the latest version.
2. I don't want to add lots of static files into the code and update them later. There are some other ways to pack them into the Python library. Maybe downloading static files in the packaging stage or use the post-installation hook.

**Comment by luolingchun** [comment]
Thank you, I have stored static files into my project, and have implemented offline swagger and redoc (refer to your source code and add two routes)

**Comment by ariciputi** [comment]
Hi,
I was looking for a way to serve the swagger/redoc static files without relaying on CDNs. In my case my app runs in an environment in which the outgoing requests to CDNs can be blocked.

@luolingchun can you elaborate on how you solved this? @kemingy are you willing to accept a PR adding an optional configuration for an alternative source for static files?

Thanks

**Comment by luolingchun** [comment]
@ariciputi You can go to my GitHub homepage，find the `flask-openapi3` project and read the source code。The idea is to use `blueprint` manage the swagger/redoc static files。

**Comment by ariciputi** [comment]
@luolingchun thanks.
