### ISSUE TITLE
[New Feature] Add a description to the tag

### ISSUE THREAD

**Issue by luolingchun** [0b01001001/spectree#120]
I read the source code of tags：

```python
...
                for tag in func_tags:
                    if tag not in tags:
                        tags[tag] = {"name": tag}
...
```

https://github.com/0b01001001/spectree/blob/v0.4.2/spectree/spec.py#L212

Please consider adding a **description** field to the tag(Because I want to describe the tag in Chinese)，just like official documents：
https://swagger.io/specification/

**. . .**

## Tag Object

Adds metadata to a single tag that is used by the Operation Object. It is not mandatory to have a Tag Object per tag defined in the Operation Object instances.

Fixed Fields
Field Name | Type | Description
-- | -- | --
name | string | REQUIRED. The name of the tag.
**description** | string | A short description for the tag. CommonMark syntax MAY be used for rich text representation.
externalDocs | External Documentation Object | Additional external documentation for this tag.

**. . .**

**Comment by kemingy** [comment]
Check #122
