### ISSUE TITLE
[BUG] 'api.validate' doesn't work on GET endpoints

### ISSUE THREAD

**Issue by mortymacs** [0b01001001/spectree#135]
**Describe the bug**
`@api.validate` doesn't work on `GET` requests.

**To Reproduce**
The sample code in https://github.com/0b01001001/spectree/blob/master/examples/falcon_demo.py#L56

```
    @api.validate(tags=[demo])
    def on_get(self, req, resp):
```

**Expected behavior**
I expect at least It supports validation over `query` but not for the request body as GET doesn't have any request body.

**Error Message**
```
{
  "title": "Invalid JSON",
  "description": "Could not parse an empty JSON body"
}
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Version ArchLinux

**Python Information (please complete the following information):**
 - Python Version Python=3.9.5
 - Library Version spectree=v0.5.0
 - Other dependencies falcon=3.0.1

**Additional context**

**Comment by kemingy** [comment]
Thanks for your feedback. This is due to some changes in falcon 3. Will fix this later.

**Comment by mortymacs** [comment]
The PR is ready https://github.com/0b01001001/spectree/pull/137

**Comment by Michae1Weiss** [comment]
This error is still present.

```
@api.validate(tags=[catalogue]) 
def on_get_list(self, req, resp):
    pass
```

```
{
  "title": "Invalid JSON",
  "description": "Could not parse an empty JSON body"
}
```

Without `@api.validate(tags=[catalogue]) ` this endpoint works fine

How can I get around this error and why does it occur?

**Comment by mortymacs** [comment]
Yes, the issue still exists. It's under progress: https://github.com/0b01001001/spectree/pull/141
