### ISSUE TITLE
[BUG] Redoc is showing a rogue "Authentication" section

### ISSUE THREAD

**Issue by scott2b** [0b01001001/spectree#152]
**Describe the bug**
In the section headers in the left navigation, Redoc shows a section called Authentication, even if no Authentication tags are defined. If endpoints are defined with an Authentication tag, another Authentication section is created.

**To Reproduce**
 - Create a spectree spec
 - 
**Expected behavior**
No undefined sections

**Python Information (please complete the following information):**
 - Python==3.8.10
 - spectree>=0.5.1

**Comment by kemingy** [comment]
Thanks for your feedback. Can you help me check if #153  fix this?

**Comment by Vlczech** [comment]
@kemingy: Sorry for that mistake :innocent:  I can confirm, that this section has gone now after I commented security_scheme in my code (and was here without whit fix with commented security_scheme) :+1:
