### ISSUE TITLE
[QUESTION] Logging validation errors

### ISSUE THREAD

**Issue by danstewart** [0b01001001/spectree#155]
I'm struggling to log validation errors.

I've tried setting the log level on the backend and the config but no luck
```python3
import logging
spectree.backend.logger.setLevel(logging.DEBUG)
spectree.config.logger.setLevel(logging.DEBUG)
```

Found PR #38 which added a log call to flask_plugin but I don't see that anymore.

I also looked at the Falcon example as advised in the README but I'm still not sure how to get the logs out.

Do I need to create a custom `JSONValidator` to get the log?

Thanks

**Comment by danstewart** [comment]
Got it working using hooks
```
def after_hook(req, resp, err, _):
    if err:
        logger.error(err)


spectree.after = after_hook
```
Is this the suggested way or is there a better way?

Thanks

**Comment by kemingy** [comment]
> Do I need to create a custom JSONValidator to get the log?

No.

> Is this the suggested way or is there a better way?

Yes, this is the suggested way. You can find that the default handler is used to get the log https://github.com/0b01001001/spectree/blob/e3b3b94b9c56f64e983f8bfefd845e01a930d320/spectree/utils.py#L123-L140.

You can register this handler when you create the `SpecTree` instance, or add the handler to a specific endpoint in `spec.validate()`.

**Comment by danstewart** [comment]
Thanks for the info!
