### ISSUE TITLE
[FEATURE REQUEST] Return pydantic model directly and skip validation

### ISSUE THREAD

**Issue by danstewart** [0b01001001/spectree#160]
Hi,

Is there any way to return pydantic models directly, or to skip the validation?

I tend to do something like
```python3
@v.get('/echo')
@api.validate(query=m.EchoReq, resp=Response(HTTP_200=m.EchoRes), tags=['example'])
def echo():
    """Replies with the queried text value"""
    message = request.context.query.text
    result = m.EchoRes(result=message)
    return result.json()
```

This doesn't play nicely with pydantic `alias`-es though.

I _think_ the issue is that my model returns the real name and then the spectree validation fails since pydantic expected the alias name.

Can I skip the validation part but keep the route-to-model association for the doc generation?

Thanks

**Comment by kemingy** [comment]
Thanks for your feedback.

One way to solve this is that you can return a raw JSON instead of building an instance of `pydantic.BaseModel` and get the JSON. (So actually the service will validate the returned data twice)

For example: `return jsonify(alias_name=message)`. Let me know if this helps.

**Comment by danstewart** [comment]
Thanks - will give that a try.

Main reason I'm using the models directly is I have some logic that converts SQLAlchemy instances into the models (basically the pydantic ORM mode).

Would this be a feature you would consider if I submit a PR?

**Comment by kemingy** [comment]
> Would this be a feature you would consider if I submit a PR?

Yeah, sure.

**Comment by danstewart** [comment]
Hi, just to let you know I still intend on doing this - I just haven't had the time yet.

**Comment by kemingy** [comment]
> Hi, just to let you know I still intend on doing this - I just haven't had the time yet.

Sure. Take your time.
