### ISSUE TITLE
How to add multiple fields in security?

### ISSUE THREAD

**Issue by dmitry-engineer** [0b01001001/spectree#161]
I want to add multiple fields in one auth flow in Swagger. As a result, expected TWO fields (partner-id and token for example) and ONE button "Authorize"

**Comment by kemingy** [comment]
Sorry, I don't get what you mean. Can you provide some examples?

**Comment by dmitry-engineer** [comment]
Yes, sure thing! Now I have the following security schema:
```
security_schemes=[
        SecurityScheme(
            name="PartnerID",
            data={"type": "apiKey", "name": "partner-id", "in": "header"},
        ),
        SecurityScheme(
            name="PartnerToken",
            data={"type": "apiKey", "name": "partner-access-token", "in": "header"},
        ),
    ]
```
And security attribute in endpoint validation 
```
security={"PartnerID": [], "PartnerToken": []}
```

 I have the button "Autorize" In Swagger. When I click it, there are 2 forms for authorization in the modal window. The first form is for PartnerID and the second one is for PartnerToken. But I need one form with 2 fields

**Comment by dmitry-engineer** [comment]
There are 2 authorization methods, but I need 1 authorization method with 2 these fields (PartnerID and partner-access-token)

**Comment by kemingy** [comment]
Correct me if I'm wrong. I think you are looking for https://swagger.io/docs/specification/authentication/#multiple.

I think that's a bug in the code. Furthermore, I'll try to fix this.

Also, I found that the swagger frontend always shows two authorization fields, no matter they are AND or OR. But the lock icon is different. AND required two fields to be filled, while OR only requires one of them.

**Comment by kemingy** [comment]
Now you can do this:

```py
# AND
validate(security=[{key1: [], key2: []}])
# OR
validate(security=[{key1: []}, {key2: []}])
```

**Comment by dmitry-engineer** [comment]
Thank you for the speed! When it will be released so I can add new version in my requirements file?

**Comment by kemingy** [comment]
> Thank you for the speed! When it will be released so I can add new version in my requirements file?

https://github.com/0b01001001/spectree/releases/tag/v0.6.1
