### ISSUE TITLE
Structure of validation error response

### ISSUE THREAD

**Issue by dmitry-engineer** [0b01001001/spectree#165]
Is it possible to change the structure of a response when we have a validation error? I'd like to create my own error handling standard and it would be nice to have the opportunity to change your existing structure

**Comment by kemingy** [comment]
> Is it possible to change the structure of a response when we have a validation error?

Yes. Check the `before` and `after` handler.

Test example: https://github.com/0b01001001/spectree/blob/6752970d2b58a0dae937c1af75eac990fde91896/tests/test_plugin_flask.py#L21-L23

Doc: https://spectree.readthedocs.io/en/latest/utils.html#spectree.utils.default_after_handler

**Comment by dmitry-engineer** [comment]
Cool, thank you
