### ISSUE TITLE
[BUG] Global security is overriden by each endpoint security option + wrong format

### ISSUE THREAD

**Issue by Vlczech** [0b01001001/spectree#166]
Issue is described in comment of incorrect fix: https://github.com/0b01001001/spectree/commit/59de4b6c02a1cd833a1fcf52d8e045a27ba2f79c#commitcomment-56433449

**Comment by kemingy** [comment]
@Vlczech Thanks for your feedback. Please help me check if #167 fix this.

**Comment by Vlczech** [comment]
@kemingy: OK, i will check, but give me please few days - I'll get to that at the earliest next week

**Comment by kemingy** [comment]
> @kemingy: OK, i will check, but give me please few days - I'll get to that at the earliest next week

No problem. Take your time.

**Comment by Vlczech** [comment]
I tested it on our code, including some modification in security (no security and so on) and now it seems OK on our code :+1:
