### ISSUE TITLE
Setting Swagger fields in `info`

### ISSUE THREAD

**Issue by dhruvkb** [0b01001001/spectree#189]
**Describe the bug**
Swagger provides the option to define many more fields under `info` such as:
- `termsOfService`
- `license`
  - `license.name`
  - `license.url`
- `contact`
  - `contact.email`
 
There is no documented way to set these fields in the generated Swagger file.

**Expected behavior**
There should be a way to configure these fields.

**Python Information (please complete the following information):**
 - Python v3.10.1
 - Spectree v0.6.8
 - Falcon v3.0.1

**Comment by kemingy** [comment]
Thanks for your feedback.

* Ref: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#info-object

Will find a time to support this.

**Comment by kemingy** [comment]
Hi @dhruvkb, this feature has been supported.

You can try it with version >= 0.7.0

Check the example: https://github.com/0b01001001/spectree/blob/a2125ccfa8af046f51b5a47ed2f6cdbed2a41fbe/examples/falcon_demo.py#L14-L20

**Comment by dhruvkb** [comment]
@kemingy am I correct in understanding that it only supports the following fields?

- title
- version
- description
- termsOfService
- contact
- license

**Comment by kemingy** [comment]
@dhruvkb Correct. According to the [OpenAPI Spec - Info](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#info-object)
