### ISSUE TITLE
[BUG] Paragraph formatting is removed from openapi.json

### ISSUE THREAD

**Issue by DataGhost** [0b01001001/spectree#198]
When I annotate an operation in this way:

```def on_post(self, req, resp):
"""Title

paragraph 1

paragraph 2
"""
```

It actually ends up in openapi.json as `{"summary": "Title", "description": "paragraph 1 paragraph 2", ...}` and the entire description is shown on one line in both ReDoc and Swagger:

### Title

paragraph 1 paragraph 2

Obviously I'd like my paragraph formatting to be maintained. A workaround is adding `<br />` instead of newlines but that seems like a bunch of unnecessary clutter with possibly faulty assumptions on the way the spec is going to be displayed.

I have traced the cause of this problem to https://github.com/0b01001001/spectree/blob/a4f5321c946acbd27515988d4c44ba44ef63ab08/spectree/utils.py#L39
Here, all newlines are replaced by spaces. This was introduced in https://github.com/0b01001001/spectree/pull/175 and looking at the diff, it seems like a change in behaviour compared to before that PR, while it did not state addressing this for any reason. Commenting out that line correctly (IMHO) leaves the newlines in and the result becomes `{"summary": "Title", "description": "paragraph 1\n\nparagraph 2", ...}`, which correctly renders my desired formatting in both ReDoc and Swagger.

It seems to be an attempt at replacing newlines (purely those due to maximum line length) by spaces so single line breaks in the comment don't show up in the resulting description, however that has the side effect of removing all intentional formatting using newlines. Probably a better way to go around this is splitting the description into paragraphs where they are broken by multiple newlines, then replacing the remaining single newlines by spaces in each paragraph, and finally joining the result again. I have attached a patch that does this and works fine for me.

[docstring_paragraphs.patch.txt](https://github.com/0b01001001/spectree/files/8032292/docstring_paragraphs.patch.txt) -- edit: revised patch in https://github.com/0b01001001/spectree/issues/198#issuecomment-1033977452

**Comment by xordoquy** [comment]
Same here.
Seems related to https://github.com/0b01001001/spectree/commit/fe12b69e1748e1988b9db15fe8cb312580d0da65 which replaces all the `\n` with spaces.

**Comment by DataGhost** [comment]
Actually, just tinkering with it now, I think the entire line with the call to `strip()` should be removed as well. The `inspect.getdoc(func)` call already removes most superfluous whitespace by uniformly removing indentation on the left side. Calling `strip()` on top of this also removes any extra whitespace at the beginning of a line, effectively making inline code blocks impossible. Removing the call to `strip()` still yields proper openapi.json output but enables those code blocks again.

Revised patch:
[docstring_paragraphs_v2.patch.txt](https://github.com/0b01001001/spectree/files/8034611/docstring_paragraphs_v2.patch.txt)

**Comment by kemingy** [comment]
Thanks for your feedback @DataGhost.

> Actually, just tinkering with it now, I think the entire line with the call to `strip()` should be removed as well. The `inspect.getdoc(func)` call already removes most superfluous whitespace by uniformly removing indentation on the left side. Calling `strip()` on top of this also removes any extra whitespace at the beginning of a line, effectively making inline code blocks impossible. Removing the call to `strip()` still yields proper openapi.json output but enables those code blocks again.

You are right. The `inspect.getdoc()` will call `cleandoc()` function. I think we don't need to clean it again.

Your patch v2 looks good to me. Feel free to create a PR.
