### ISSUE TITLE
[BUG] Use on a nested function resulted in index error.

### ISSUE THREAD

**Issue by punkneverdie** [0b01001001/spectree#202]
**Describe the bug**

Use the decorator on a nested function results in the following error:
```
# NOTE: If func is a `HTTPEndpoint`, it should have '.' in its ``__qualname__``
        # This is not elegant. But it seems `inspect` doesn't work here.
        funcname = func.__qualname__
        instance = args[0] if "." in func.__qualname__ else None
>       request = args[1] if "." in func.__qualname__ else args[0]
E       IndexError: tuple index out of range
```

**To Reproduce**
```
def function_a():

    app = Starlette(debug=True)

    spectree = SpecTree("starlette")

    @app.route("/health")    
    @spectree.validate(
        resp=Response(HTTP_200=None),
        tags=["Health check"])
    async def health(request):
        """
        health endpoint

        returns 200 if service is up and accessible
        """
        return PlainTextResponse("OK")
    
    spectree.register(app)

    return app
```

**Expected behavior**
The should work for nested function that is not in a HTTPEndpoint class. If it must check the `__qualname__`, it should also check the size of args[].

**Desktop (please complete the following information):**
 - OS: Linux on a docker container
 - Version: 5.10.76-linuxkit

**Python Information (please complete the following information):**
 - Python Version [e.g. Python=3.10]
 - Library Version [e.g. spectree=0.7.3]
 - Other dependencies [e.g. starlette=0.18.0]

**Comment by kemingy** [comment]
Hi @punkneverdie, thanks for your feedback.

Will try to fix this ASAP.

**Comment by punkneverdie** [comment]
Awesome, thanks!
