### ISSUE TITLE
[Bug] supporting json array in request body 

### ISSUE THREAD

**Issue by dima-engineer** [0b01001001/spectree#204]
When I try to send an array as a request body, I get an exception.
```
def request_validation(self, request, query, json, headers, cookies):
        req_query = request.args or {}
        if request.mimetype in self.FORM_MIMETYPE:
            req_json = request.form or {}
            if request.files:
                req_json = dict(
                    list(request.form.items()) + list(request.files.items())
                )
        else:
            req_json = request.get_json(silent=True) or {}
        req_headers = request.headers or {}
        req_cookies = request.cookies or {}
        request.context = Context(
            query.parse_obj(req_query.items()) if query else None,
>           json.parse_obj(req_json.items()) if json else None,
            headers.parse_obj(req_headers.items()) if headers else None,
            cookies.parse_obj(req_cookies.items()) if cookies else None,
        )
E       AttributeError: 'list' object has no attribute 'items'
```

**Comment by dima-engineer** [comment]
If I understand correctly, the library doesn't support JSON array body for now at all. It means that every request to the endpoints with array in body are going to trow this exception

**Comment by kemingy** [comment]
Hi @dima-engineer, thanks for your feedback. Can you provide a minimal reproducible example?

**Comment by dima-engineer** [comment]
class SomeModel(BaseModel):
    __root__: List[int]


@bp.route('/some-path', methods=['POST'])
@api.validate(json=SomeModel)
def example():
    return "Hello"

**Comment by dima-engineer** [comment]
Request body:
```
[
  0
]
```

**Comment by dima-engineer** [comment]
Thank you for thunderbold-fast answer @kemingy

**Comment by kemingy** [comment]
I see. I forget JSON body can be a list and `pydantic` supports `__root__`.

Will fix this. Thanks.

**Comment by dima-engineer** [comment]
Appreciate it

**Comment by dima-engineer** [comment]
Yep! That works for me

**Comment by dima-engineer** [comment]
Hi @kemingy, could you please create a release with this fix?

**Comment by alexted** [comment]
I think it sounds like a problem https://github.com/0b01001001/spectree/issues/96

**Comment by kemingy** [comment]
> I think it sounds like a problem #96

This one is related to PyPy support caused bugs.
