### ISSUE TITLE
[BUG] `json` data required for GET request

### ISSUE THREAD

**Issue by yedpodtrzitko** [0b01001001/spectree#226]
**Describe the bug**
`GET` requests cant provide data for `json` property of `validate()`, so it shouldnt be required/validated, but it seems to happen right now. See example below.

**To Reproduce**
consider following endpoint (in `tests/test_plugin_flask.py`). 
This view can handle `GET` request or `POST` request. `json` property is relevant only for `POST` request, however even `GET` request trigger its validation:
```
@app.route("/api/no_response", methods=["GET", "POST"])
@api.validate(
    json=Query,
)
def no_response():
    return {}
```

```
resp = client.get("/api/no_response")
assert resp.status_code == 200
```

**Error message**
```
AssertionError: b'[{"loc":["order"],"msg":"field required","type":"value_error.missing"}]\n
```

**Comment by kemingy** [comment]
Hi @yedpodtrzitko, thanks for your contribution.

My colleagues tested positive for Covid-19 last weekend. I also had lunch with them. I don't feel very well but haven't confirmed yet. I may need to take a rest. Will try to review it as soon as possible.

**Comment by yedpodtrzitko** [comment]
This sure can wait, I hope you'll get well soon 🤞
