### ISSUE TITLE
Can the email validator dependency be optional?

### ISSUE THREAD

**Issue by MarkKoz** [0b01001001/spectree#235]
`EmailStr` is used for the contact info, but the field is optional. It's a waste to install these additional dependencies if I don't plan on supplying a value for this field, and don't plan on using `EmailStr` for my own API's models. Or maybe I do want to supply an email in the contact info, but don't value validation of it enough to justify the additional dependencies.

Is there a nice way to make this dependency optional? Of course, it could just be an extra for spectree, but will that feel awkward or unintuitive for users?

**Comment by kemingy** [comment]
Not sure how to make it optional. Even if you don't install the `email-validator`, there won't be an error until you call the `EmailStr` validation. Deleting it from the requirements file also works for most users.

But `email-validator` is a single file library without any other dependencies. I guess it's still okay to keep it here.

Feel free to propose a nicer way to handle it.

**Comment by MarkKoz** [comment]
> Deleting it from the requirements file also works for most users.

I'm not sure if I understood you. If I clone spectree and modify `requirements.txt` beforehand, then yes, that works. But it's not a practical solution.

> But email-validator is a single file library without any other dependencies. I guess it's still okay to keep it here.

It has two dependencies: https://github.com/JoshData/python-email-validator/blob/main/setup.cfg#L27-L29

> Feel free to propose a nicer way to handle it.

I'm not sure what to do about avoiding installing the email validator. If spectree stops installing it by default, then it will be a breaking change. Otherwise, the following code could be used.

```py
# spectree/config.py
from pydantic import EmailStr

try:
    EmailStr.validate("a@b.com")
except ImportError:
    EmailStr = str
```

**Comment by MarkKoz** [comment]
Well, maybe not quite a breaking change, but it would be misleading for users that didn't get the memo on email validation no longer being enabled by default.

**Comment by kemingy** [comment]
> > But email-validator is a single file library without any other dependencies. I guess it's still okay to keep it here.
> 
> It has two dependencies: https://github.com/JoshData/python-email-validator/blob/main/setup.cfg#L27-L29

Thanks for pointing it out. I forgot the `setup.cfg` file.

I guess most users won't be affected by this change.

Feel free to open a PR.

**Comment by MarkKoz** [comment]
Sure, I can make a PR. But what exactly is the change you're agreeing to? That the email validator becomes optional along with the code above e.g. `pip install spectree[email]`, akin to `pip install pydantic[email]`?

**Comment by kemingy** [comment]
Thanks for your help.

Make the `email-validator` optional with `pip install spectree[email]`.
