### ISSUE TITLE
Deactive validation_error_status value

### ISSUE THREAD

**Issue by Joseda8** [0b01001001/spectree#240]
Is there a way to remove the `validation_error_status` feature for specific endpoints? 

Use case: A `GET` endpoint with no query parameters but path parameters only, so it will never be possible to return a `422` or any error with the `ValidationError` form.

**Comment by yedpodtrzitko** [comment]
Hi,
I read this a few times but I'm still not sure if I fully understand what's the issue. Could you give a specific example where/how is `validation_error_status` causing the issue? Thanks

**Comment by yedpodtrzitko** [comment]
feel free to reopen the issue with update.
