### ISSUE TITLE
Werkzeug error

### ISSUE THREAD

**Issue by dmitry-engineer** [0b01001001/spectree#246]
I'm trying to use your library with Werkzeug==2.2.0 but getting error:
```
 File "/usr/local/lib/python3.7/site-packages/spectree/plugins/flask_plugin.py", line 62, in parse_path
    from werkzeug.routing import parse_converter_args, parse_rule
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing'
```
Could it be resolved?
Thank you

**Comment by kemingy** [comment]
* Thanks for your feedback. This is fixed in #244.
* We are planning to release the `v1.0.0` so you can try the latest version with `pip install --pre spectree`. This should fix the werkzeug bug.

**Comment by dmitry-engineer** [comment]
Ah, yes. I see, thank you very very much

**Comment by dmitry-engineer** [comment]
Have you thought about implementation your library for Quart framework?

**Comment by dmitry-engineer** [comment]
It's almost the same as Flask but ASGI

**Comment by kemingy** [comment]
> Have you thought about implementation your library for Quart framework?

I'll open an issue to track this. But I cannot promise when I will work on that.

**Comment by kemingy** [comment]
I created a new release https://github.com/0b01001001/spectree/releases/tag/v0.10.4 so users who run `pip install spectree` will also get this fix.

Closing this.
