### ISSUE TITLE
feat: support `quart` (ASGI `flask`)

### ISSUE THREAD

**Issue by kemingy** [0b01001001/spectree#247]
- [ ] support [quart](https://github.com/pallets/quart)

**Comment by dmitry-engineer** [comment]
I will fork your repository and try to do this as well when I will have free time. I really love your library and I want to help in any way that I can.

**Comment by kemingy** [comment]
> I will fork your repository and try to do this as well when I will have free time. I really love your library and I want to help in any way that I can.

Thanks. Feel free to ask questions here.

**Comment by dima-engineer** [comment]
Hi! Could you please check my branch? This is something like a fast solution for Quart support. Not so elegant as it could be, honestly. But I tested it and seems like it works. https://github.com/0b01001001/spectree/compare/master...dima-engineer:spectree:dmitry/quart-plugin

**Comment by dima-engineer** [comment]
I had to use nest-async as a workaround for async support. Otherwise, I'm afraid that there should the whole library to be overwritten.

**Comment by kemingy** [comment]
Thanks for your contribution! This PR will take some time to review. I'll try to give some feedback as soon as possible.

**Comment by kemingy** [comment]
> I had to use nest-async as a workaround for async support. Otherwise, I'm afraid that there should the whole library be overwritten.

You don't need to use `nest-async` in this library. For the async support, you can refer to the implementation of falcon async plugin: https://github.com/0b01001001/spectree/blob/a065c04e3c532733155d2bb9abe9169cda38f3fe/spectree/plugins/falcon_plugin.py#L254

Also, quart plugin should inherit from flask plugin, since they share a lot of the same code.

**Comment by dima-engineer** [comment]
Ok. I will check on FalconAsgiPlugin. Thank you

**Comment by dima-engineer** [comment]
Hi @kemingy ! Finally I found time to fix the quart plugin according to the comments you left above.
https://github.com/0b01001001/spectree/compare/master...dima-engineer:spectree:dmitry/quart-plugin
See, please!

**Comment by yedpodtrzitko** [comment]
@dima-engineer can you open a pull request from the branch please? It's easier to comment on the code that way. Thanks.

**Comment by dima-engineer** [comment]
Sure! Here you go
https://github.com/0b01001001/spectree/pull/262

**Comment by dima-engineer** [comment]
There are several methods which overlap FlaskPlugin methods only because of different imports at the beginning of the method. I'm wondering if we can avoid this somehow
