### ISSUE TITLE
Potentially leaky tests

### ISSUE THREAD

**Issue by gwaramadze** [0b01001001/spectree#283]
When I was contributing I noticed a strange behavior when testing. It can be easily reproduced:
```
pytest
```

this is green, but this:
```
pytest -k test_two_endpoints_with_the_same_path
```

gives
```
FAILED tests/test_spec.py::test_two_endpoints_with_the_same_path - RuntimeError: Working outside of application context.
```

I don't have much time to investigate, but it is something you might want to take a look at as it indicates that at least one test relies on a global scope.

**Comment by kemingy** [comment]
Thanks for your feedback. Will fix this.
