### ISSUE TITLE
Key appended to Schema Component

### ISSUE THREAD

**Issue by AndreasBBS** [0b01001001/spectree#300]
When the openapi.json is generated by spectree the schema components have a key appended to them, for example: `Pet.acc87c7`; I'd like it to be generetated as `Pet`. Is there a way to disable the key appendage?

**Comment by kemingy** [comment]
It's generated by https://github.com/0b01001001/spectree/blob/78edc00241006832f32a0e569e7a27844ca9aa38/spectree/utils.py#L235-L244

The purpose is to avoid the same class name defined in different files.

For now, there is no elegant way to disable it. You can patch this function. Or you may strip the suffix. Depends on your requirements.

**Comment by AndreasBBS** [comment]
I understand I can fork but I was trying to avoid having to do that. I understand the goal of avoiding having the same class defined in different files.

My use case is that I'm using tools on my API clients to convert the openapi component schemes into types/classes (for example: [openapi-typescript](https://github.com/drwpow/openapi-typescript)). So is it your opinion that this tools should remove the prefix when naming the classes? I'm not sure this prefixing behavior is something defined in the OpenAPI specification so it might not be fair to expect libraries that consume OpenAPI specifications to be able to handle it.

Thanks for the quick reply. I really appreciate that!

**Comment by kemingy** [comment]
I see your points. I think there is no spec for this.

One possible way to make it easier is moving the related functions to the `BasePlugin` static methods. So people can inherit and override part of the methods. We can do this step by step. If you're interested in this, you can refactor this `get_model_key` function.

Similar to https://github.com/0b01001001/spectree/pull/297#discussion_r1156158690

**Comment by AndreasBBS** [comment]
I've been looking at the code to try to implement this refactor but I found some issues with moving it to BasePlugin static methods.

In `response.py` I don't seem to have access to the current plugin/backend like I do in the Spectree class:
https://github.com/0b01001001/spectree/blob/78edc00241006832f32a0e569e7a27844ca9aa38/spectree/response.py#L137

Any suggestion to what to do here?

**Comment by AndreasBBS** [comment]
> I've been looking at the code to try to implement this refactor but I found some issues with moving it to BasePlugin static methods.
> 
> In `response.py` I don't seem to have access to the current plugin/backend like I do in the Spectree class:
> 
> https://github.com/0b01001001/spectree/blob/78edc00241006832f32a0e569e7a27844ca9aa38/spectree/response.py#L137
> 
> Any suggestion to what to do here?

This is only used in tests as far as I can tell so I'll go ahead and do the refactor and we can keep discussing how we can refactor the tests.
