### ISSUE TITLE
bug: don't support pydantic v2

### ISSUE THREAD

**Issue by bekishev04** [0b01001001/spectree#328]
### Describe the bug

When i use pydantic v2:

```
assert issubclass(model, BaseModel), "invalid `pydantic.BaseModel`"
AssertionError: invalid `pydantic.BaseModel`
```
code line:
https://github.com/0b01001001/spectree/blob/master/spectree/response.py#L76

### To Reproduce

```
class ResponseMessage(BaseModel):
    """Response Message"""

    message: str


@spec_tree.validate(
        resp=Response("HTTP_401", HTTP_200=schemas.ResponseMessage),
    )
    def get(self):
        pass
```

### The spectree version

spectree = "^1.2.0"
pydantic = {extras = ["email"], version = "^2.1.1"}

### Additional context

You can fix it in this file:

https://github.com/0b01001001/spectree/blob/master/spectree/_pydantic.py

There we use only version 1 of pydantic and dont use the second version

**Comment by kemingy** [comment]
Currently, you might need to `from pydantic.v1 import BaseModel` when you're using pydantic v2.

It's tricky to support both v1 and v2.

**Comment by kemingy** [comment]
Ref to https://github.com/0b01001001/spectree/pull/319#pullrequestreview-1510211443

We might need to refactor some parts.

**Comment by bekishev04** [comment]
> Currently, you might need to `from pydantic.v1 import BaseModel` when you're using pydantic v2.
> 
> It's tricky to support both v1 and v2.

i understand. But when know i want using V2 pydantic. And cant do it with spectree. 

I think it would be useful to write in readme  that spectree only supports version 1 including the first version from pedantic v2

**Comment by bekishev04** [comment]
yYu can close the issue if you think it is necessary, I have received my answer. I was just counting on full v2 support

**Comment by kemingy** [comment]
Let me create another issue to track the full v2 support.
