### ISSUE TITLE
bug: field alias no longer respected (regression)

### ISSUE THREAD

**Issue by divad** [0b01001001/spectree#352]
### Describe the bug

Before spectree 1.2.4 the response respected the `alias` argument to pydantic's `Field` class. We have a response class with a "schema" attribute, which of course you can't have because it conflicts with pydantic's `.schema` attribute, so we used an alias:

```
class ModelExample(BaseModel, extra=Extra.forbid):
    schema_: str = Field(description='The data type of the field.', alias='schema')
```

With the alias the resulting returned data was actually returned as `schema` rather than `schema_`.

As of spectree 1.2.4 this no longer works, instead the returned json has the field as `schema_` - thus the alias is ignored. We actually return a python data structure (a dict) rather than instances of the pydantic model itself, so somehow spectree is rewriting the name of the field in the dictionary we are returning.

### To Reproduce

Use a model like this:

```
class ModelExample(BaseModel, extra=Extra.forbid):
    schema_: str = Field(description='The data type of the field.', alias='schema')
```

and have the view return a dict containing `schema` as the key.

### Expected behavior

The alias is respected

### The spectree version

spectree 1.2.4
python 3.11

**Comment by kemingy** [comment]
Hi, I checked the code diff but didn't find the related commit. This sounds like something related to the `pydantic.BaseModel.dict(by_alias=True)`. Ref https://docs.pydantic.dev/1.10/usage/exporting_models/#modeldict

It might also related to the way you return the response. May I know which framework (flask/falcon/starllete) are you using? How you return the response in your handler?

**Comment by divad** [comment]
We use Flask. As for the how we return, we just return a plain dictionary

```
return {'this': 'that', 'schema': 'this'}
````
(this isn't the real code, but I'm not allowed to copy/paste that, but that's how it works)

**Comment by kemingy** [comment]
I agree that spectree should not modify what the view returns (when it's already a valid response). This change is due to that the response might be a BaseModel which is not a valid JSON body. Will fix this later.

**Comment by divad** [comment]
many thanks :raised_hands: 

also apologies, I feel I came off as rude in this ticket, that was not my intention.
