### ISSUE TITLE
bug: List[int] in query params does not accept a list of size 1 in flask app

### ISSUE THREAD

**Issue by melvincaraangJC** [0b01001001/spectree#355]
### Describe the bug

I have a Flask app using spectree to validate payloads. One of my use cases is an API endpoint that accepts query parameters to filter out resources.

When I define `List[int]` in my model for a field named `id_list`, I get an error ONLY IF the size of the list is 1 e.g. `https://mysite.com/api/v1/samples?id_list=1` will fail but `https://mysite.com/api/v1/samples?id_list=1&id_list=2` will succeed

### To Reproduce

1. Install the following:

```python
pydantic==2.4.2
pydantic_core==2.10.1
spectree==1.2.6
flask==2.3.2
```

2. Run this app:
```python
from typing import List
from flask import Flask, jsonify
from pydantic.v1 import BaseModel, Field
from spectree import SpecTree


class SampleQueryParams(BaseModel):
    id_list: List[int] = Field(..., description="List of IDs")


app = Flask(__name__)
spec = SpecTree("flask")


@app.route("/api/v1/samples", methods=["GET"])
@spec.validate(query=SampleQueryParams)
def get_samples():
    return jsonify(text="it works")


if __name__ == "__main__":
    spec.register(app)  # if you don't register in api init step
    app.run(port=8000)

```

3. Make a GET request to `http://localhost:8000/api/v1/samples?id_list=1`

### Expected behavior

The response payload should be `{"text":"it works"}`, but it is returning `[{"loc":["id_list"],"msg":"value is not a valid list","type":"type_error.list"}]`

### The spectree version

Output of `pip show spectree`:

```
Name: spectree
Version: 1.2.6
Summary: generate OpenAPI document and validate request&response with Python annotations.
Home-page: 
Author: 
Author-email: Keming Yang <kemingy94@gmail.com>
License: Apache-2.0
Location: /Users/melvincaraang/.venvs/qbench/lib/python3.9/site-packages
Requires: pydantic
Required-by: 
```

Output of `uname -a`

```
Darwin Melvins-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:46:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T8101 x86_64
```

Output of `python --version`

```
Python 3.9.18
```

Output of `python show flask`

```
Name: Flask
Version: 2.3.2
Summary: A simple framework for building complex web applications.
Home-page: 
Author: 
Author-email: Armin Ronacher <armin.ronacher@active-4.com>
License: BSD-3-Clause
Location: /Users/melvincaraang/.venvs/qbench/lib/python3.9/site-packages
Requires: blinker, click, importlib-metadata, itsdangerous, Jinja2, Werkzeug
Required-by: Flask-Caching, Flask-Cors, Flask-HTTPAuth, Flask-Limiter, Flask-Login, Flask-WeasyPrint
```

**Comment by kemingy** [comment]
Thanks for your report.

It's a bit tricky to support this since there is no standard for query parameter parsing. It heavily depends on the implementation of the framework. In `flask`, it's a `ImmutableMultiDict`. The value will be a list when the key shows up more than once. Otherwise, it's a single value instead of a list of values.

There are several solutions:
1. defining `id_list: Union[int, List[int]]`.
2. define customized validation for the `SampleQueryParams` that can convert `int` to `List[int]`
3. detect the field type and convert it in spectree

I'll try the 3rd one. Before it's released, you can try the rest two solutions.

**Comment by melvincaraangJC** [comment]
I appreciate the quick turnaround on this! I upgraded my spectree version and it works as expected now. However, I'm still experiencing the original issue if I define `Optional[List[int]]`.

Is this still a bug or do I need to define it differently? I apologize for reopening this ticket, I'm a bit new to the library so I'm still learning
