### ISSUE TITLE
[BUG] validation of array[]-like parameter in query string

### ISSUE THREAD

**Issue by yedpodtrzitko** [0b01001001/spectree#39]
**Describe the bug**
Hi,
consider the following model and request:

```python
class StatsQuery(BaseModel):
    events: List[Literal["CREATED", "DEACTIVATED"]]
```

~/stats?events[]=CREATED&events[]=DEACTIVATED~

edit above:
```
/stats?events=CREATED&events=DEACTIVATED
```

**Expected behavior**
- request validation will pass

**Error Message**
```
[
  {
    "loc": [
      "events"
    ], 
    "msg": "value is not a valid list", 
    "type": "type_error.list"
  }
]
```

**Python Information (please complete the following information):**
 - Python 3.8.0
 - spectree==0.3.0
 - Flask==1.1.1

**Additional context**

For now I'm using this ugly wokaround: in `FlaskPlugin.validate()`:

```diff
-arg = request.args or {}
+arg = request.args.to_dict(flat=True) or {}
+if arg:
+    for field_name, field_info in query.schema()['properties'].items():
+        if field_info['type'] == 'array':
+            arg[field_name] = request.args.getlist(field_name)
```

**Comment by kemingy** [comment]
Thanks for your feedback.

You almost make it. Can try

```py
arg = request.args.to_dict(flat=False) or {}
```

Then this will introduce another problem: all the values are list. So I have to write a function to unwrap all the single-element-list.

By the way, you don't need to add `[]` in the query. It seems this is not how Werkzeug does.

**Comment by yedpodtrzitko** [comment]
> Can try `request.args.to_dict(flat=False)`

that was the first thing I tried, but as you said - everything is a list afterwards. 

> So I need to write a function to unwrap all the single-element-list.

this is not as easy - how do you tell apart what's an actual list with one item, and what should be unwrapped?

> By the way, you don't need to add [] in the query.

that's the way how axios/vuejs send it by default.

**Comment by kemingy** [comment]
You are right. We need to find a clean solution for unwrapping.

> that's the way how axios/vuejs sends it by default.

https://stackoverflow.com/a/24728298/6037286 I guess there is no standard for this. So let's keep it the same as what framework does.

**Comment by kemingy** [comment]
I have checked the query in `flask`, `falcon`, `starlette`, and found that:

* `flask`: `MultiDict`
* `falcon`: `dict` (value will be a list if there are multiple values for a key)
* `starlette`: `ImmutableMultiDict`

There is an issue in FastAPI about query format for a list of elements: https://github.com/tiangolo/fastapi/issues/739. Another issue about complex type in the query: https://github.com/tiangolo/fastapi/issues/884.

And it seems FastAPI has the same problem: cannot handle `List` in the HTTP query.

I can add a `root_validator(pre=True)` to the `pydantic` Model to handle this issue, but it will definitely slow down the speed. I don't know if it's possible to handle this in a clean way without harming the validation speed.

Since there is no RFC about how to use `List` in the HTTP query, and different web frameworks have different ways to handle this. It's really hard to decide. And I'm not sure if it worth?

**Comment by yedpodtrzitko** [comment]
Hi, thanks for digging into this. I am also afraid there's no silver bullet for this issue due to the support of multiple frameworks. As such, I'd leave it up to each individual to handle it as needed per their use-case. Here's a few things which would make it easier for me when I was monkeypatching that myself:

- I had to inherit `FlaskPlugin` and copypaste the whole `validate()`, where I added those few lines shown in the first message of this issue. That's about 30 lines copy-pasted from the original, which I would need to check each time I upgrade Spectree to see if anything has changed there.
This would be easier if there would be another method, something like `extract_request`, which would only return all the things from request as it's done now, but I could override just that without touching `validate()` at all. Something like this:

```diff
class FlaskPlugin(BasePlugin):

    def validate(...):
        ...
-        arg = request.args or {}
-        data = request.get_json() or {}
-        head = request.headers or {}
-        cook = request.cookies or {}
+        arg, data, head, cook = self.extract_request(...)
        ...

+    def extract_request(...):
+        arg = request.args or {}
+        data = request.get_json() or {}
+        head = request.headers or {}
+        cook = request.cookies or {}
+        return arg, data, head, cook
```

Then I had to inherit `SpecTree` itself too, since there's no way how to use there a custom backend directly, as `backend_name` makes lookup in `spectree.plugins.PLUGINS`, so I had to do this:

```
class SpecTreePatched(SpecTree):

    def __init__(self, backend_name="base", app=None, **kwargs):
        super(SpecTreePatched, self).__init__(backend_name, app, **kwargs)
        # set custom `backend` now
        self.backend = FlaskPluginPatched(self)
```

It would be nice here either to pass a custom `backend` into the constructor, or make `spectree.plugins.PLUGINS` somehow extendable easily, so I can pass custom `backend_name`, which would be found in `PLUGINS`.

**Comment by kemingy** [comment]
Thanks for your advice. I have created a PR #41 for this. Please help check it.

**Comment by yedpodtrzitko** [comment]
That was fast. I'll close this issue now, and move further discussion into the MR.
