### ISSUE TITLE
Adopt Black for code formatting?

### ISSUE THREAD

**Issue by yedpodtrzitko** [0b01001001/spectree#42]
Hello again,
[Black](https://github.com/python/black) is becoming the de facto a standard for formatting Python code. By following the rule "if you can automate it, automate it", this can eliminate some tedious manual formatting, and enforce uniform code style from other potential contributors.

How would you feel about it?

**Comment by kemingy** [comment]
Currently, I'm using [autopep8](https://github.com/hhatto/autopep8). I'm not sure which one is better. I'll do some research later. My personal Python coding style is derived from:

* [PEP8](https://www.python.org/dev/peps/pep-0008/)
* [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html)
* [The Hitchhiker’s Guide: Code Style](https://docs.python-guide.org/writing/style/)

In the [CONTRIBUTING](https://github.com/0b01001001/spectree/blob/master/.github/CONTRIBUTING.md) file, format check is required before PR. This one is [flake8](https://flake8.pycqa.org/en/latest/). I know this is not comprehensive.
