### ISSUE TITLE
Async Falcon support?

### ISSUE THREAD

**Issue by onecrayon** [0b01001001/spectree#45]
I'm currently experimenting with Falcon 3.0.0a1 and was wondering if you have plans to add an async Falcon plugin for SpecTree (3.0 will support both WSGI and ASGI applications)?

If not, this might be something I would be interesting in contributing since I really like that SpecTree provides a way to both handle input/output (de)serialization with Pydantic *and* autogenerates an OpenAPI document similar to FastAPI. What would your preferred method of implementing this? A completely separate plugin, a subclass of the existing Falcon plugin, something else?

**Comment by kemingy** [comment]
Yes. I'm waiting for the stable release.

For what I know, to support the async part we only need to implement an async validator. So I prefer to reuse other methods. If possible, I hope we can make some changes to the current Falcon plugin class or create a subclass.

If you are interested, here are some changes you may need to pay attention to:
* https://github.com/0b01001001/spectree/blob/acdf875bb7247d2b050588f836e8f2ed93deeae5/spectree/spec.py#L84-L96 This implementation is not elegant.
* You can take a look at the https://github.com/0b01001001/spectree/blob/master/spectree/plugins/starlette_plugin.py part. Meanwhile, you can help me check if the current implementation is correct.

**Comment by onecrayon** [comment]
> Yes. I'm waiting for the stable release.

Heh, fair enough.

> For what I know, to support the async part we only need to implement an async validator. So I prefer to reuse other methods. If possible, I hope we can make some changes to the current Falcon plugin class or create a subclass.

I'll see what I can cobble together as I continue to hack away at this project, and will submit a PR if I find something that seems useful. I agree that having two different validation functions isn't particularly elegant.
