### ISSUE TITLE
[BUG] Query parameters default values can be found in openapi.json but don't show up in docs.

### ISSUE THREAD

**Issue by zero-shubham** [0b01001001/spectree#47]
Query parameters default values can be found in openapi.json but don't show up in docs.

![Docs](https://user-images.githubusercontent.com/17028205/84585708-1871dd00-ae30-11ea-80f1-1d7275474dbb.png)
![openapi.json](https://user-images.githubusercontent.com/17028205/84585709-1a3ba080-ae30-11ea-83fd-3ac6c1c50f57.png)

**Comment by zero-shubham** [comment]
I have a fix, may i create a PR? 

Below is the needed code change, Idea is for query we will only pass on BaseModel, so it's properties should added in the schema rather than the BaseModel itself.
![Code to change](https://user-images.githubusercontent.com/17028205/84586182-e3b45480-ae34-11ea-8a35-47c39fca169d.png)

Below is the result.
![Selection_276](https://user-images.githubusercontent.com/17028205/84586200-15c5b680-ae35-11ea-90a3-dc88d45006bf.png)

**Comment by kemingy** [comment]
Thanks for your feedback. I'm checking this problem.

This problem is more complex than I thought. We need to consider nested models. For example:

```py
class Language(str, Enum):
    en = 'en-US'
    zh = 'zh-CN'

class Header(BaseModel):
    Lang: Language
```

I feel that it still needs to be a schema instead of all the keys here.

**Comment by zero-shubham** [comment]
Aha when query has to be an enum.. Got it. Will look into too. Thanks!

**Comment by kemingy** [comment]
https://stackoverflow.com/a/46172865

This may help you. In swagger, default value is different from example values. While redoc can handle this very well.

**Comment by zero-shubham** [comment]
In my PR i did a mistake, following is how "required" should be evaluated
![required_evaluation](https://user-images.githubusercontent.com/17028205/84589346-706a0d00-ae4b-11ea-81b2-18b90076747a.png)

By nested models if meant the following, I think it works fine. Sorry if I understood this wrong.
![Selection_277](https://user-images.githubusercontent.com/17028205/84589370-94c5e980-ae4b-11ea-85d6-ab9c4dbf8cb5.png)

![Selection_279](https://user-images.githubusercontent.com/17028205/84589371-9c858e00-ae4b-11ea-9807-de6f491f284d.png)

![Selection_280](https://user-images.githubusercontent.com/17028205/84589373-a1e2d880-ae4b-11ea-9f2c-f537d81ce019.png)

**Comment by kemingy** [comment]
> Do not confuse example values with default values. An example illustrates what the value is supposed to be. A default value is what the server uses if the client does not provide the value.

https://swagger.io/docs/specification/adding-examples/

Using default values in the example is not the standard way. Try to use examples.

Check the `pydantic` doc: https://pydantic-docs.helpmanual.io/usage/schema/#schema-customization

**Comment by zero-shubham** [comment]
Oh now i understand what you wanted to say sorry, but i do want it to be default values and not example values. like mentioned here - https://swagger.io/blog/api-development/unlocking-the-spec-the-default-keyword/

**Comment by kemingy** [comment]
> The second case is using the default as a way to mention a sample value for its container. That is not the proper use of the field and can lead to unexpected behavior in some of the Swagger tools. Some containers offer alternative ways to setting a sample value.

Quoted from the "Common mistakes when using the default value".

**Comment by kemingy** [comment]
But you reminded me that I should unwrap the `query` schema, which will make the example uses the default value when no example is provided. This is related to the Swagger schema example bug.

Check this PR https://github.com/0b01001001/spectree/pull/49/files#diff-989812b700f0968eb753c6323c557140R47-R55.

Again, you should not treat the default values as examples because it's not the standard way, and that may be changed in the future for Swagger.

**Comment by zero-shubham** [comment]
I think i need better deep understanding of OpenAPI specs, thanks.
And yes unwrapping query parameter will acheive what i wanted.
You did a great job with this project!
