### ISSUE TITLE
Default description for 422 Unprocessable Entity response

### ISSUE THREAD

**Issue by honeydev** [0b01001001/spectree#55]
Hi, i use your library in several work projects with flask. And each project i add description for default 422 HTTP Error again and again. Maybe, we can add default exception model?
My solution looks like this:
https://github.com/0b01001001/spectree/compare/master...honeydev:add-422-default-description?expand=1
And we have description out of box :
![Screenshot_20200906_235336](https://user-images.githubusercontent.com/20888582/92324219-101dec80-f083-11ea-9442-ef0f24069695.png)

Thanks!

**Comment by kemingy** [comment]
Thanks for your feedback. You can create a PR for this.

Here is something you need to check:

* https://github.com/0b01001001/spectree/blob/49d85ec20b7c3756a774c10e32d7be248a7b2a14/spectree/utils.py#L94-L95 this can prevent overwriting users' customized 422 error
* https://github.com/samuelcolvin/pydantic/blob/296d929904735690af85e4af71a5ddbdbf8e7885/pydantic/error_wrappers.py#L109-L123 you missed some attributes

**Comment by honeydev** [comment]
Okay, i'll try

**Comment by kemingy** [comment]
Can check the version [v0.3.11](https://github.com/0b01001001/spectree/releases/tag/v0.3.11)
