### ISSUE TITLE
[BUG] Authorization header not usable in Swagger UI

### ISSUE THREAD

**Issue by samyhajal** [0b01001001/spectree#56]
**Describe the bug**
When defining a custom header model with a field `Authorization`,
```
class RequestHeader(BaseModel):
    Authorization: str
```
and using it as such:
```
@api_validator.validate(headers=RequestHeader)
def query():
    ...
```

the rendered openapi.json contains `Authorization` as a parameter:
```
"parameters": [
          {
            "in": "header", 
            "name": "Authorization", 
            "required": true, 
            "type": "string"
          }
        ], 
```

which is unusable, because it is restricted by swagger-ui per https://swagger.io/docs/specification/describing-parameters/#header-parameters: "Note: Header parameters named Accept, Content-Type and Authorization are not allowed"

**To Reproduce**
See pydantic model above. To server the swagger UI, I'm using `flask-swagger-ui`.

**Expected behavior**
I'd expect the restricted headers (Accept, Content-Type and Authorization) to be formatted not as parameters, but as their corresponding OpenAPI keywords per https://swagger.io/docs/specification/describing-parameters/#header-parameters

**Error Message**
No error message from SpecTree, but in Swagger UI, the Authorization header is NOT sent in the request when executing the request.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Catalina

**Python Information (please complete the following information):**
 - Python Version: 3.7.2
 - Library Version spectree=`v0.3.3`
 - Other dependencies: `flask-swagger-ui==3.25.0`

Let me know if you need more information. Awesome project btw!

**Comment by kemingy** [comment]
Thanks for your feedback. I'll try to find a solution.
