### ISSUE TITLE
[FEATURE] objects passed into validate() to be accessible in endpoint

### ISSUE THREAD

**Issue by natasha-aleksandrova** [0b01001001/spectree#58]
Coming from flask_pydantic library, spectree has similar signature using validate() function and providing models for validation.

However, in flask_pydantic you get access to your model directly and in spectree it gets converted to dictionary from an object. It would be nice to persist that object.

Example:
```
@api_spec.validate(json=BodyModel, resp=Response(HTTP_200=ResponseModel), tags=["push"])
def push(account: str):
    # request.json is a dictionary
    # would like access to BodyModel with request data in here
```

**Comment by kemingy** [comment]
This can be accessed with `request.context.json`.

**Comment by natasha-aleksandrova** [comment]
@natasha-aleksandrova I get a dictionary not the pydantic model object

**Comment by natasha-aleksandrova** [comment]
@kemingy thank you!!! I was using request.json not through context - it works!
