### ISSUE TITLE
[BUG] swagger 2.0 errors 

### ISSUE THREAD

**Issue by natasha-aleksandrova** [0b01001001/spectree#66]
**Describe the bug**

I'm using this library to generate swagger:2.0 spec and ran into few issues with the generated spec via .spec attribute.

1. editor.swagger.io expects `swagger: '2.0'` for the version instead of the generated `openapi: '2.0'`
2. under paths, the correct key is `operationId` but generated version has `operationID` which errors out as invalid 
```
should NOT have additional properties
additionalProperty: operationID
```

**To Reproduce**
```
SpecTree('flask', title="API", path="docs", openapi_version="2.0").spec
```

**Expected behavior**
a valid swagger data for 2.0 version

**Python Information (please complete the following information):**
 - Python Version [ Python=3.6]
spectree==0.3.6

**Additional context**
I'm happy to submit a PR if allowed to fix above issues as long as the maintainer agrees with above issues.

**Comment by kemingy** [comment]
> I'm using this library to generate swagger:2.0 spec and ran into few issues with the generated spec via .spec attribute.

May I know the reason to use 2.0 instead of 3.0?

>     1. editor.swagger.io expects `swagger: '2.0'` for the version instead of the generated `openapi: '2.0'`

Yeah, this needs to be `swagger: '2.0'` or `openapi: '3.0.n'`

>     2. under paths, the correct key is `operationId` but generated version has `operationID` which errors out as invalid

> ```
> should NOT have additional properties
> additionalProperty: operationID
> ```

> **Additional context**
> I'm happy to submit a PR if allowed to fix above issues as long as the maintainer agrees with above issues.

Welcome PR. To make it compatible with swagger 2.0, maybe we need to do a lot of work. Check the official document about the difference between swagger 2.0 and OpenAPI 3.0: https://swagger.io/blog/news/whats-new-in-openapi-3-0/ .

**Comment by natasha-aleksandrova** [comment]
After spending some time on this yesterday, yes too many changes to make it support 2.0 as well.

We use Google Endpoints which only supports 2.0 version, it's a gateway service that uses openapi spec (in this case 2.0).


I have another workaround for making it work with google endpoints.. but operationID is only invalid in openapi3.0 and should be fixed to operationId.

**Comment by kemingy** [comment]
> After spending some time on this yesterday, yes too many changes to make it support 2.0 as well.

OK. Maybe we don't have to do this now.

> We use Google Endpoints which only supports 2.0 version, it's a gateway service that uses openapi spec (in this case 2.0).
>
> I have another workaround for making it work with google endpoints.. but operationID is only invalid in openapi3.0 and should be fixed to operationId.

I see. Then you can create a PR to fix this. Thanks.

**Comment by kemingy** [comment]
> **Additional context**
> I'm happy to submit a PR if allowed to fix above issues as long as the maintainer agrees with above issues.

I think this can be fixed by changing this line: https://github.com/0b01001001/spectree/blob/baf1f8bd5fe5679dc2b21cbddc67c482c77c50a8/spectree/spec.py#L166

Feel free to submit a PR.

**Comment by natasha-aleksandrova** [comment]
Ive got fixes in my fork just haven't had a chance to get the PR going - will submit a fix shortly. Thanks!
