### ISSUE TITLE
[BUG]can not get params by application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by csy18** [0b01001001/spectree#83]
when frontend pass params using application/x-www-form-urlencoded, spectree can not get params by query, is there any other ways to get it?
![截屏2020-11-18 上午10 42 59](https://user-images.githubusercontent.com/60063723/99476404-767c9080-298b-11eb-80f1-021d79309522.png)
![截屏2020-11-18 上午10 48 06](https://user-images.githubusercontent.com/60063723/99476496-9d3ac700-298b-11eb-9f58-fc4746f7316f.png)
![截屏2020-11-18 上午10 48 24](https://user-images.githubusercontent.com/60063723/99476507-a2981180-298b-11eb-9653-df8d202df8bc.png)

I just find the code using request.args and request.json to get params, however request.values or request.form not use.
![截屏2020-11-18 上午10 37 00](https://user-images.githubusercontent.com/60063723/99476702-fdca0400-298b-11eb-8a07-cc28c363b450.png)

**Comment by kemingy** [comment]
Thanks for your feedback.

When you use `application/x-www-form-urlencoded`, the data is in the body. This is different from call `GET localhost:8000/?user=hello&msg=hello&index=1`. That's why you cannot get it from the `request.args`.

But flask provides a `request.form` to support this behavior, which is not a very common. Instead, sending data in a JSON format with `application/json` is more general. Because usually the response is also in the JSON format.

In Postman, you should use `form-data`.

Back to this question, of course I can detect the content type and try to get data from `request.form`. But I guess in this way I should store it in `json` instead of `query`. (I know the name `json` is not very proper, because the data can be any type, check #53)

**Comment by csy18** [comment]
> Thanks for your reply.
> 
> When you use `application/x-www-form-urlencoded`, the data is in the body. This is different from call `GET localhost:8000/?user=hello&msg=hello&index=1`. That's why you cannot get it from the `request.args`.
> 
> But flask provides a `request.form` to support this behavior, which is not a very common. Instead, sending data in a JSON format with `application/json` is more general. Because usually the response is also in the JSON format.
> 
> In Postman, you should use `form-data`.
> 
> Back to this question, of course I can detect the content type and try to get data from `request.form`. But I guess in this way I should store it in `json` instead of `query`. (I know the name `json` is not very proper, because the data can be any type, check #53)

**Comment by csy18** [comment]
> Thanks for your reply.
> 
> When you use `application/x-www-form-urlencoded`, the data is in the body. This is different from call `GET localhost:8000/?user=hello&msg=hello&index=1`. That's why you cannot get it from the `request.args`.
> 
> But flask provides a `request.form` to support this behavior, which is not a very common. Instead, sending data in a JSON format with `application/json` is more general. Because usually the response is also in the JSON format.
> 
> In Postman, you should use `form-data`.
> 
> Back to this question, of course I can detect the content type and try to get data from `request.form`. But I guess in this way I should store it in `json` instead of `query`. (I know the name `json` is not very proper, because the data can be any type, check #53)



> Thanks for your feedback.
> 
> When you use `application/x-www-form-urlencoded`, the data is in the body. This is different from call `GET localhost:8000/?user=hello&msg=hello&index=1`. That's why you cannot get it from the `request.args`.
> 
> But flask provides a `request.form` to support this behavior, which is not a very common. Instead, sending data in a JSON format with `application/json` is more general. Because usually the response is also in the JSON format.
> 
> In Postman, you should use `form-data`.
> 
> Back to this question, of course I can detect the content type and try to get data from `request.form`. But I guess in this way I should store it in `json` instead of `query`. (I know the name `json` is not very proper, because the data can be any type, check #53)

now I need to get params by `application/x-www-form-urlencoded`, but I can not get it by spectree, would you like to provide this function?

**Comment by kemingy** [comment]
> now I need to get params by application/x-www-form-urlencoded, but I can not get it by spectree, would you like to provide this function?

Yes, it's possible. I'll try to detect the content type. So if you use `application/x-www-form-urlencoded`, the data will be parsed and store in `json`.

Let me create a PR for this.

**Comment by kemingy** [comment]
@csy18 try version 0.3.12
