### ISSUE TITLE
[BUG] query works error

### ISSUE THREAD

**Issue by sunlin92** [0b01001001/spectree#88]
**Describe the bug**
query always fails validation.

**To Reproduce**
```python
from flask import Flask, request, jsonify
from pydantic import BaseModel
from spectree import SpecTree, Response

class Q(BaseModel):
    q: str


app = Flask(__name__)
api = SpecTree('flask')


@app.route('/api/user', methods=['GET'])
@api.validate(query=Q, resp=Response(HTTP_200=Q, HTTP_403=None), tags=['api'])
def user_profile():
    print(request.context.query)
    return jsonify(q='it works')


if __name__ == "__main__":
    api.register(app)
    app.run(port=8000)

```

**Expected behavior**
```Response body
[
  {
    "loc": [
      "q"
    ],
    "msg": "str type expected",
    "type": "type_error.str"
  }
]
```
**Error Message**
![image](https://user-images.githubusercontent.com/40912737/101596834-c1d90a80-3a30-11eb-832a-9f09967e103a.png)

**Desktop (please complete the following information):**
 - OS [Linux]
 - Version [Debian 10]

**Python Information (please complete the following information):**
 - Python Version [ Python=3.6.9]
 - Library Version [ spectree=0.3.13]
 - Other dependencies [flask=1.1.2]

**Comment by kemingy** [comment]
Hi, I tried your example on macOS 10.15.7, but I can't reproduce this error. I don't think it's related to OS.

Can you try:

* run the `curl` command on your terminal
* print the request arguments with the `before` handler

```python
def before_handler(req, resp, req_validation_error, instance):
    print(request.args)

@api.validate(query=Q, resp=Response(HTTP_200=Q, HTTP_403=None), tags=['api'], before=before_handler)
```

**Comment by sunlin92** [comment]
Thanks.
I switched the version of Python from 3.6.9 (Pypy) to 3.9.0 (Cpython) and it works.

**Comment by kemingy** [comment]
Interesting question. I tried PyPy and got the same error. I found that this is caused by the `pydantic.BaseModel.parse_obj` applied to the `werkzeug.ImmutableMultiDict`.

I'll create a PR to fix this.

Thanks for your feedback.

**Comment by kemingy** [comment]
Try the latest version: 0.3.14. This should work with pypy.
