### ISSUE TITLE
[BUG] Pydantic custom root doesn't work as expected

### ISSUE THREAD

**Issue by i404788** [0b01001001/spectree#94]
**Describe the bug**
Using `__root__` from pydantic doesn't work in falcon (json).

**To Reproduce**
Create a Model with custom `__root__` as described in https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types.

Example:
```
class Model(BaseModel):
    __root__: Dict[str, str]
```

It seems that spectree doesn't recognize `__root__` as a special entry.
```py
{'a': 'b'} # Doesn't work

{'__root__': {'a': 'b'}} # Does work
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Python Information (please complete the following information):**
 - Python Version Python=3.6
 - Library Version spectree=0.3.15
 - Other dependencies falcon=3.0.1a

I'm currently using WSGI (waitress-serve) with falcon.

**Comment by kemingy** [comment]
Here is an example:

```python
from wsgiref import simple_server
import falcon
from pydantic import BaseModel
from typing import Dict
from spectree import SpecTree


class Req(BaseModel):
    __root__: Dict[str, str]


api = SpecTree('falcon')


class Index:
    @api.validate(json=Req)
    def on_post(self, req, resp):
        print(req.context.json)
        resp.media = {'msg': 'ok'}


if __name__ == "__main__":
    app = falcon.App()
    api.register(app)
    app.add_route('/', Index())

    httpd = simple_server.make_server("localhost", 8000, app)
    httpd.serve_forever()
```

So if I send a request with [httpie](httpie.org): `http ':8000/' hello=world`, I will get the correct output.

```
>> __root__={'hello': 'world'}
>> 127.0.0.1 - - [11/Dec/2020 22:57:26] "POST / HTTP/1.1" 200 13

HTTP/1.0 200 OK
Date: Fri, 11 Dec 2020 14:57:26 GMT
Server: WSGIServer/0.2 CPython/3.6.10
content-length: 13
content-type: application/json

{
    "msg": "ok"
}
```

Maybe you can provide an example to reproduce the bug?

**Comment by i404788** [comment]
The error is in response validation.

```py3
import falcon
from pydantic import BaseModel
from typing import Dict
from spectree import SpecTree, Response

spectree = SpecTree('falcon', title='OB Trader API', version='v1')


class GetResp(BaseModel):
    __root__: Dict[str, str]


class Test:
    @spectree.validate(resp=Response(HTTP_200=GetResp))
    def on_get(self, req, resp):
        resp.media = {'a': 'b'}

api = falcon.App()
api.add_route('/api/test', Test())
```

With both `waitress-server` and `gunicorn` it will give back: 
```
[{"loc": ["__root__"], "msg": "field required", "type": "value_error.missing"}]
```

**Comment by kemingy** [comment]
I see. I think this is caused by `BaseModel.validate()`. I should use `BaseModel.parse_obj()` instead. Will create a PR to fix this.

Thanks.
