### ISSUE TITLE
[BUG]Openapi.json cannot be properly loaded when host includes sub-domain

### ISSUE THREAD

**Issue by nervecell23** [0b01001001/spectree#97]
**Describe the bug**
Openapi.json cannot be properly loaded when host includes sub-domain

**To Reproduce**
For example:
Given the hostname: http://123.4.0.0/api/
Access the doc: http://123.4.0.0/api/apidoc/swagger
The Swagger UI will attempt to load the openapi.json at /apidoc/openapi.json where the json does not exist

**Expected behavior**
The Swagger UI should attempt to load the openapi.json at:
/api/apidoc/openapi.json

**Error Message**
Unable to render definition

**Others**
The test feature is also unusable, because the Swagger UI use the wrong Request-URL:
http://123.4.0.0 instead of http://123.4.0.0/api/

**Comment by kemingy** [comment]
For the swagger part, if you set up the path `SpecTree('flask', path='api/apidoc')`, you should be able to access the swagger page in `<URL>/api/apidoc/swagger`.

For the web query part, if you need all the route paths begin with `/api`, you'd better use a blueprint with route `/api`.

**Comment by nervecell23** [comment]
Thank you for the reply! I followed your suggestion but the issue persists.
Currently my host is: `http://123.4.0.0/api`
I tried: `SpecTree(path='api/apidoc')`, however by doing that, the endpoint of the Swagger page would become the following:
`http://123.4.0.0/**api/api**/apidoc/swagger`
Also, the Swagger UI would attempt to load openapi.json at `http://123.4.0.0/api/apidoc/openapi.json`, while the json file is actually located at `http://123.4.0.0/api/api/apidoc/`

**Comment by kemingy** [comment]
Can you provide some code to reproduce this error? So I can help you find a solution.

**Comment by nervecell23** [comment]
I'm sorry I cannot provide you with any code. To reproduce the error, please image an host with subdomain, for example:
**www.myhost.com/api:7000**

**Comment by nervecell23** [comment]
Thanks again for the help. I've changed the DNS setting to use a host without encoded forward slash, which should solve the problem.
